version: '3.4'

services:
  XDelivered.Starter.Core.EF.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro